export const LOGIN = 'LOGIN';
export const LOGIN_IS_LOADING = 'LOGIN_IS_LOADING';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_TOKEN = 'GET_TOKEN';
export const TOKEN_IS_LOADING = 'TOKEN_IS_LOADING';
export const HANDLE_TOKEN_ERROR = 'LOGIN_TOKEN_ERROR';
export const SAVE_TOKEN = 'GET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const ADD_USERINFO = 'ADD_USERINFO';
export const HANDLE_USERINFO_ERROR = 'HANDLE_USERINFO_ERROR';
export const USERINFO_IS_LOADING = 'USERINFO_IS_LOADING';

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_CONTRACTOR_PROJECTS = 'GET_CONTRACTOR_PROJECTS';
export const PROJECT_IS_LOADING = 'PROJECT_IS_LOADING';
export const HANDLE_PROJECT_ERROR = 'HANDLE_PROJECT_ERROR';


export const GET_ALL_USER_NOTIFICATION = 'GET_ALL_USER_NOTIFICATION';
export const NOTIFICATION_IS_LOADING = 'GET_ALL_USER_NOTIFICATION_LOADING';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATIONS';
