# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SelaMobile2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  # Pods for SelaMobile2

  # target 'SelaMobile2-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'



  pod 'react-native-video', :path => '../node_modules/react-native-video'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'SelaMobile2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SelaMobile2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SelaMobile2-tvOS

  target 'SelaMobile2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
